
export const Routes = {
    // pages
    DashboardOverview: { path: "/dashboard/overview" },
    Settings: { path: "/settings" },
    YeniIlan: { path: "/yeniIlan" },
    IlanAra: { path: "/ilanAra" },
    RaporEnCokArananlar: { path: "/tables/raporEnCokArananlar" },
    RaporEnCokBulunanlar: { path: "/raporEnCokBulunanlar" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    IlanListesi: { path: "/tables/ilanListesi" },
    BasvuruListesi: { path: "/tables/basvuruListesi" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};