
export const Routes = {
    // pages
    DashboardOverview: { path: "/dashboard/overview" },
    HesapBilgileri: { path: "/hesapBilgileri" },
    Profil: { path: "/Profil" },
    YeniIlan: { path: "/yeniIlan" },
    IlanDetay: { path: "/ilanDetay" },
    IlanAra: { path: "/ilanAra" },
    ElemanAra: { path: "/elemanAra" },
    YeniKategori: { path: "/yeniKategori" },
    KategoriDetay: { path: "/KategoriDetay" },
    RaporEnCokArananlar: { path: "/tables/raporEnCokArananlar" },
    RaporEnCokBulunanlar: { path: "/raporEnCokBulunanlar" },
    IlanListesi: { path: "/tables/ilanListesi" },
    BasvuruListesi: { path: "/tables/basvuruListesi" },
    KategoriListesi: { path: "/tables/kategoriListesi" },
    Billing: { path: "/examples/billing" },
    KullaniciGiris: { path: "/kullaniciGiris" },
    KullaniciKayit: { path: "/kullaniciKayit" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },
};